### ISSUE TITLE
emitter bug with multiple events in v6.0.0

### ISSUE THREAD

**Issue by padjon** [FlippieCoetser/Events#1]
Hello, im using this module via npm and v 6.0.0, which is the latest but different than the code i see here.

Anyways, i have some issues with the emit-method:
`    Event.prototype.emit = function (event) {
        var a = [];
        for (var _i = 1; _i < arguments.length; _i++) {
            a[_i - 1] = arguments[_i];
        }
        var listeners = this._listeners.filter(function (item) { return item.event === event; });
        /* istanbul ignore next */
        listeners.forEach(function (item) { return item.listener.apply({}, a || []); });
        this._listeners = listeners.filter(function (item) { return !item.once; });
        return listeners.length !== 0 ? true : false;
    };`

The listeners are first filtered by the ones being relevant to the event. Afterwards, this ones are filtered by the ones, which are called only once. Afterwards we assign the result to our this._listeners variable.

Now all listeners which are called once are removed and **all listeners from other events.** 
So one event removes all listeners of any other event

**Comment by padjon** [comment]
a fix would be to replace line 19 by
` this._listeners = this._listeners.filter(function (item) { return !(item.once && item.event === event); });`

**Comment by FlippieCoetser** [comment]
@padjon thanks for the feedback. I currently travel but will be able to implement your suggestion in two weeks. You are also welcome to make a pull request which I can merge via mobile phone.

**Comment by padjon** [comment]
I would love to, but why is the code i got from npm (v6.0.0) differ that much from the code in the repository? Which is the current code? I have seen that the issue also exists in the git repository's code.

**Comment by FlippieCoetser** [comment]
@padjon I rewrote the entire library but not update the NPM. With the new Typescript language features I will rewrite is again. for example String Enums is not support.... Once back I will do it and let you know. for now have a look at the build in Event Library in Node. it should be exactly the same

**Comment by padjon** [comment]
Thank you for clarification @FlippieCoetser 
No hustle because of me, i fixed it locally.

**Comment by FlippieCoetser** [comment]
@padjon you might want to upgrade to the latest version 7.9.0 as I have rewritten the entire library.
I also added a Test for the bug you recorded. Thanks for filing the bug!

Test
```Typescript
describe("Given: once(eventName, listener)", () => {
        it("When on(eventName2, listener2) and emit(eventName) and emit(eventName2) then listener2() should be called", () => {
            let event = new Event();
            let listener = sinon.spy();
            let eventName = "eventName";
            let listener2 = sinon.spy();
            let eventName2 = "eventName2";
            event.once(eventName, listener);
            event.on(eventName2, listener2);
            event.emit(eventName);
            event.emit(eventName2);
            expect(listener2).to.have.been.calledOnce;
        });
});
```
