### ISSUE TITLE
With release 7.8.0 parameters are not passed any longer

### ISSUE THREAD

**Issue by Dreaded-Gnu** [FlippieCoetser/Events#2]
Hello,

with the latest release, the parameters are not passed any longer when calling emit with parameter. When I register a handler via `once( 'event', ( data:any ) => { console.dir( data ); })` and call somewhere in my project `emit( 'name', { 'somedata': '1' } )`, the bound event listener doesn't receive the data, which should be passed as parameter.

As far as I see the problem is the call of the once listener here: https://github.com/FlippieCoetser/Events/blob/1313c654ae507f715ca0efdea247eebd992b9b16/src/events.ts#L83

When I change the built javascript to apply `arguments` the data is passed as it should be: `return listener.apply( void 0, arguments );`

Or is this an expected behaviour? The current solution for me is switching back to release 6.0.0 as of there anything worked as expected for me.

**Comment by FlippieCoetser** [comment]
@Dreaded-Gnu The entire library was rewritten after version 6.0.0 so upgrading to 7.9.0 is advisable.
I have added a Test and a Fix in version 7.9.0 Thanks for reporting that.

Test
```Typescript
        it("When emit(eventName, arg) then listener should be called with arg", () => {
            let event = new Event();
            let listener = sinon.spy();
            let eventName = "eventName";
            let arg = "agr";
            event.once(eventName, listener);
            event.emit(eventName, arg);
            expect(listener).to.have.been.calledOnce;
            expect(listener).to.have.been.calledWith(arg);
```

Fix
```Typescript
private _createOnceListener(listener: Listener, eventName: string): Listener {
        let newListener = (...args) => {
            this.removeListener(eventName, listener);
            return listener(...args);
        };
        return newListener;
    }
```
`args` was not passed into the newListener.
